### ISSUE TITLE
Generate documentation in subdirectory

### ISSUE THREAD

**Issue by vuilehaid** [libgit2/docurium#21]
How do you have to setup the Docurium config file such that it outputs the documentation in a subdirectory? It is mentioned on the home page that it is possible, but I can't find out how to do it.

**Comment by fsaintjacques** [comment]
Can we re-open this feature? I agree that crawling tags is a mandatory feature, but writing the output in a gh-branches is a strong github-ism. It would be really useful to validate output before pushing into documentation branch, i.e. writing to a local directory.

**Comment by niess** [comment]
Agreed. What I am doing at moment is overwriting to a temporary dev branch. Then I merge manually to the gh-pages once I am happy with the result. But being able to dump to a local dir would be more convenient.

**Comment by carlosmn** [comment]
This is very oriented towards GitHub because it was made by a hubber for a project hosted on GitHub. If you'd like to define an interface for writing things out, I can take a look at the PR, but it's not something I'm going to do myself, since I won't be using that feature.
